# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  publish = "build/"
  command = "yarn build"
  environment = { ACCESS_TOKEN = "super secret", NODE_VERSION = "8.0.1" }

  # Directory with the serverless Lambda functions to deploy to AWS.
  # functions = "project/functions/"

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
